// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STC.Data;

namespace STC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221216144946_CreateTypeConsultation")]
    partial class CreateTypeConsultation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("STC.Models.Client", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CliActive")
                        .HasColumnType("BIT")
                        .HasColumnName("CliActive");

                    b.Property<string>("CliAddressCity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliAddressCity");

                    b.Property<string>("CliAddressFull")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliAddressFull");

                    b.Property<string>("CliAddressNeighborhood")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliAddressNeighborhood");

                    b.Property<string>("CliAddressNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliAddressNumber");

                    b.Property<string>("CliAddressStreet")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliAddressStreet");

                    b.Property<DateTime>("CliBirthDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("CliBirthDate");

                    b.Property<string>("CliName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliName");

                    b.Property<string>("CliNameFather")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliNameFather");

                    b.Property<string>("CliNameMother")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliNameMother");

                    b.Property<string>("CliNote")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR(160)")
                        .HasColumnName("CliNote");

                    b.Property<string>("CliPhoneCell")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR(16)")
                        .HasColumnName("CliPhoneCell");

                    b.Property<string>("CliPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR(16)")
                        .HasColumnName("CliPhoneNumber");

                    b.Property<string>("CliSchool")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliSchool");

                    b.Property<string>("CliSchoolCity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliSchoolCity");

                    b.Property<string>("CliSchoolGrade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliSchoolGrade");

                    b.Property<string>("CliSchoolState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("CliSchoolState");

                    b.HasKey("CliId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("STC.Models.Professional", b =>
                {
                    b.Property<int>("ProfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ProfActive")
                        .HasColumnType("BIT")
                        .HasColumnName("ProfActive");

                    b.Property<string>("ProfCell")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)")
                        .HasColumnName("ProfCell");

                    b.Property<bool>("ProfConsultation")
                        .HasColumnType("BIT")
                        .HasColumnName("ProfConsultation");

                    b.Property<string>("ProfJob")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("ProfJob");

                    b.Property<string>("ProfName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("ProfName");

                    b.HasKey("ProfId");

                    b.ToTable("Professional");
                });

            modelBuilder.Entity("STC.Models.TypeConsultation", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("TypeActive")
                        .HasColumnType("BIT")
                        .HasColumnName("TypeActive");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR(40)")
                        .HasColumnName("TypeName");

                    b.Property<decimal>("TypePrice")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)")
                        .HasColumnName("TypePrice");

                    b.HasKey("TypeId");

                    b.ToTable("TypeConsultation");
                });

            modelBuilder.Entity("STC.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("NVARCHAR(220)")
                        .HasColumnName("UserEmail");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR(400)")
                        .HasColumnName("UserPassword");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
